import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { RecentPosts } from "./_components/RecentPosts";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} font-geist bg-foreground overflow-x-hidden antialiased`}
      >
        <Nav />
        <div className="flex">
          <div className="xsm:block xsm:w-[90px] sticky hidden h-dvh shrink-0 md:w-[200px]"></div>
          <main>{children}</main> 
          <RecentPosts />
        </div>
      </body>
    </html>
  );
}
